# keybindings

# --- PANES (Alt + hjkl) ---
# Direct movement between splits within the current window
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
# --- WINDOWS (Ctrl + hjkl) ---
# We use h/l for previous/next, and you can map j/c for create/kill
bind -n C-h previous-window
bind -n C-l next-window
bind -n C-j new-window
bind -n C-k confirm-before -p "kill-window #W? (y/n)" kill-window

# Others
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# Set the prefix to Ctrl-a
set -g prefix C-a
# Unbind the default Ctrl-b so you can use it for other things
unbind C-b
# Ensure you can still send Ctrl-a to apps (like Neovim) by pressing it twice
bind C-a send-prefix

# sesh config
bind -N "last-session (via sesh) " L run-shell "sesh last"
bind -n "M-s" run-shell "~/.config/tmux/scripts/sesh-picker.sh"
