# List of plugins

set -g @plugin 'tmux-plugins/tmux-sensible'
# settings
 
set -g @plugin "janoamaral/tokyo-night-tmux"
# settings
set -g @tokyo-night-tmux_theme storm

set -g @plugin 'tmux-plugins/tmux-pain-control'
# settings

# NOTE: add all plugins above this line
# don't forget to also install tmuxinator and sesh
set -g @plugin 'tmux-plugins/tpm'
# settings
# change path where plugins are installed
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.local/share/tmux/plugins/tpm/tpm'
