# ~/.config/tmux/tmux.conf

# 1. Load General Options
source-file ~/.config/tmux/conf/options.conf

# 2. Load Visual Settings
source-file ~/.config/tmux/conf/display.conf

# 3. Load Keybindings (Your custom Alt/Ctrl logic)
source-file ~/.config/tmux/conf/keys.conf

# 4. Load Plugins (Keep this at the bottom)
source-file ~/.config/tmux/conf/plugins.conf
